// Premium Curated Game Library — Upgraded
export const gamesConfig = [
    // ── BRAIN GAMES ──────────────────────────────────────
    {
        id: 'game_maze',
        title: 'Maze Runner',
        description: 'Navigate through procedurally generated mazes. Find the exit! (10 Levels)',
        category: 'brain',
        emoji: '🌀',
        maxLevel: 10,
        component: 'MazeRunner',
    },
    {
        id: 'game_king',
        title: "King's Path",
        description: 'Move a chess king across a grid, avoiding rocks to reach the crown. (10 Levels)',
        category: 'brain',
        emoji: '♛',
        maxLevel: 10,
        component: 'KingPath',
    },
    {
        id: 'game_sliding',
        title: 'Sliding Puzzle',
        description: 'Slide tiles into the correct order. Classic 15-puzzle with increasing grid sizes! (10 Levels)',
        category: 'brain',
        emoji: '🧩',
        maxLevel: 10,
        component: 'SlidingPuzzle',
    },
    // ── EDUCATIONAL GAMES ────────────────────────────────
    {
        id: 'game_wordsearch',
        title: 'Word Search',
        description: 'Find hidden words in all 8 directions across the letter grid. (10 Levels)',
        category: 'educational',
        emoji: '🔤',
        maxLevel: 10,
        component: 'WordSearch',
    },
    {
        id: 'game_math',
        title: 'Math Genius',
        description: 'Solve dynamic equations, from simple +1 to multiplication! (10 Levels)',
        category: 'educational',
        emoji: '➕',
        maxLevel: 10,
        component: 'MathQuiz',
    },
    {
        id: 'game_world',
        title: 'World Safari',
        description: 'Geography, Colors, and Country Capitals quiz! (10 Levels)',
        category: 'educational',
        emoji: '🌍',
        maxLevel: 10,
        component: 'WorldQuiz',
    },
    {
        id: 'game_spelling',
        title: 'Spelling Bee',
        description: 'Listen to the word and tap the floating letters to spell it! (10 Levels)',
        category: 'educational',
        emoji: '🐝',
        maxLevel: 10,
        component: 'SpellingBee',
    },
    // ── FUN GAMES ────────────────────────────────────────
    {
        id: 'game_memory',
        title: 'Memory Match',
        description: 'Flip and match beautiful emoji cards from memory! (10 Levels)',
        category: 'fun',
        emoji: '🎴',
        maxLevel: 10,
        component: 'MemoryMatch',
    },
    {
        id: 'game_simon',
        title: 'Simon Says',
        description: 'Watch the color/sound sequence, then repeat it back correctly. (10 Levels)',
        category: 'fun',
        emoji: '🎵',
        maxLevel: 10,
        component: 'SimonSays',
    },
    {
        id: 'game_fruit',
        title: 'Fruit Catcher',
        description: 'Catch healthy fruits in your basket, dodge the bombs! (10 Levels)',
        category: 'fun',
        emoji: '🧺',
        maxLevel: 10,
        component: 'CatchGame',
    },
];
